import type { Metadata } from 'next'
import Link from 'next/link'
import { ArrowLeft } from 'lucide-react'

type PrivacySection = {
  title: string
  paragraphs: string[]
  bullets?: string[]
}

const effectiveDate = 'February 13, 2026'

const sections: PrivacySection[] = [
  {
    title: '1. Overview',
    paragraphs: [
      'This Privacy Policy describes how Analog Research, LLC ("Analog Research," "we," "us," "our") collects, uses, stores, and shares information when you use our website, marketplace, APIs, MCP endpoint, and related services (the "Services").',
      'By using the Services, you acknowledge this Privacy Policy.',
    ],
  },
  {
    title: '2. Information We Collect',
    paragraphs: [
      'We collect information you provide, information created through marketplace activity, and technical information generated by your use of the Services.',
    ],
    bullets: [
      'Account and profile data: name, email, avatar, bio, skills, rates, availability, location, timezone, and optional social links (for example GitHub or LinkedIn).',
      'Marketplace activity: bounties, applications, bookings, disputes, reviews, support requests, and related metadata.',
      'Messages and attachments: conversation content and files you upload (for example proof attachments or message attachments).',
      'Payment and payout references: we store payment identifiers and metadata such as Stripe PaymentIntent IDs, Stripe Transfer IDs, Coinbase payment IDs, wallet addresses (if provided), and blockchain transaction hashes. We do not store full card numbers.',
      'API and MCP usage: API key metadata (stored as hashed key material plus a short prefix), scopes, rate-limit fields, and usage signals such as last-used time and last-used IP.',
      'Notification channel configs: if you add notification channels, we store the channel type and configuration (for example webhook URLs, Slack or Discord webhook URLs, or notification email addresses).',
      'Security and operational logs: IP address, timestamps, user agent, request metadata, and anti-abuse signals.',
    ],
  },
  {
    title: '3. How We Use Information',
    paragraphs: [
      'We use information to operate the Services, facilitate marketplace workflows, process payments, prevent abuse, and improve safety and reliability.',
    ],
    bullets: [
      'Create and manage accounts, profiles, and API/MCP access.',
      'Enable matching, communication, bookings, proof submission, escrow flows, dispute workflows, and reviews.',
      'Process payments and payouts through payment providers and maintain transaction records.',
      'Detect fraud, spam, phishing, and harmful activity, including link and content safety checks.',
      'Deliver notifications you request (email, webhook, Slack, Discord).',
      'Comply with legal obligations and enforce our Terms.',
    ],
  },
  {
    title: '4. Content Moderation and Safety Checks',
    paragraphs: [
      'To reduce scams and harmful content, we may analyze text, links, and metadata submitted through the Services.',
      'Some moderation and classification may be performed using third-party services (for example OpenRouter) to generate risk and spam signals. This may require sending the relevant content text to those providers.',
      'Moderation signals are not perfect. If you believe a restriction is incorrect, you may contact us for review.',
    ],
  },
  {
    title: '5. Cookies and Similar Technologies',
    paragraphs: [
      'We use cookies and similar technologies for authentication, session management, security controls, and basic product functionality.',
      'You can control cookies through your browser settings, but disabling some cookies may limit functionality.',
    ],
  },
  {
    title: '6. When We Share Information',
    paragraphs: [
      'We do not sell personal information. We share data only as needed to run the Services and comply with law.',
    ],
    bullets: [
      'With counterparties: information needed to complete a booking, communicate, and deliver work (for example messages, task context, and proof attachments shared between the Agent and Human on a booking).',
      'With service providers: hosting and infrastructure providers, Supabase (auth, database, storage), Stripe (payments), Coinbase Commerce (crypto payments), OpenRouter (moderation), Resend (email delivery), and other vendors we use to operate the Services.',
      'With your configured endpoints: if you enable notifications, we send events to your webhook URL or Slack/Discord webhook URL, or deliver email to your chosen address.',
      'For legal and safety reasons: to comply with legal process, enforce our Terms, or protect rights, safety, and platform security.',
      'As part of a merger, acquisition, financing, or asset transfer, subject to appropriate safeguards.',
    ],
  },
  {
    title: '7. Data Retention',
    paragraphs: [
      'We retain information for as long as needed to provide the Services, comply with legal and accounting obligations, resolve disputes, and enforce agreements.',
      'Retention periods vary by data type, operational needs, and legal requirements. For example, transaction records may be retained longer than marketing or preference data.',
    ],
  },
  {
    title: '8. Your Rights and Choices',
    paragraphs: [
      'Depending on your location, you may have rights to access, correct, delete, restrict, or export personal information, and to object to certain processing.',
      'You can update many profile fields in your account settings. For data rights requests, contact us at analog-research.org/contact.',
      'If you add notification channels (webhook, Slack, Discord, email), you can disable or remove them through the product or by contacting us.',
    ],
  },
  {
    title: '9. Security',
    paragraphs: [
      'We use administrative, technical, and organizational safeguards designed to protect information.',
      'No method of transmission or storage is completely secure, so we cannot guarantee absolute security.',
    ],
  },
  {
    title: '10. International Transfers',
    paragraphs: [
      'Analog Research may process and store information in countries other than your own depending on where our providers operate. Where required, we apply appropriate safeguards for cross-border data transfers.',
    ],
  },
  {
    title: '11. Children',
    paragraphs: [
      'The Services are not intended for individuals under 18. We do not knowingly collect personal information from individuals under 18.',
      'If you believe a minor has provided personal data, contact us and we will take appropriate steps.',
    ],
  },
  {
    title: '12. Policy Updates',
    paragraphs: [
      'We may update this Privacy Policy periodically. If we make material changes, we will update the effective date and post the revised version on this page.',
      'Your continued use of the Services after the effective date means the updated policy applies.',
    ],
  },
  {
    title: '13. Contact',
    paragraphs: [
      'Questions or requests related to privacy can be sent via our contact page at analog-research.org/contact.',
    ],
  },
]

export const metadata: Metadata = {
  title: 'Privacy Policy | Analog Research',
  description: 'Privacy Policy for the Analog Research marketplace and API/MCP services.',
}

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-background">
      <header className="border-b border-border">
        <div className="container mx-auto px-4 py-4 flex items-center justify-between gap-3">
          <Link href="/" className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground transition-colors">
            <ArrowLeft className="w-4 h-4" />
            Back to home
          </Link>
          <Link href="/terms" className="text-sm text-muted-foreground hover:text-foreground transition-colors">
            Terms of Service
          </Link>
        </div>
      </header>

      <main className="container mx-auto px-4 py-12">
        <div className="max-w-4xl mx-auto">
          <h1 className="text-3xl md:text-4xl font-bold mb-3">Privacy Policy</h1>
          <p className="text-sm text-muted-foreground mb-10">Effective date: {effectiveDate}</p>

          <div className="space-y-8">
            {sections.map((section) => (
              <section key={section.title} className="space-y-3">
                <h2 className="text-xl font-semibold">{section.title}</h2>
                {section.paragraphs.map((paragraph) => (
                  <p key={paragraph} className="text-muted-foreground leading-relaxed">
                    {paragraph}
                  </p>
                ))}
                {section.bullets ? (
                  <ul className="list-disc pl-5 space-y-2 text-muted-foreground">
                    {section.bullets.map((bullet) => (
                      <li key={bullet}>{bullet}</li>
                    ))}
                  </ul>
                ) : null}
              </section>
            ))}
          </div>
        </div>
      </main>
    </div>
  )
}
